active_passive_reconciler should validate all pods cross zones
cloudfoundry-incubator/quarks-statefulset pull request #21
Opened 2020-10-11 03:18 UTC by yangwenyanibm

Let `GetMaxStatefulSetVersion` to return all StatefulSet at the Max Version, and then loop through the StatefulSet list and validating pods in these StatefulSets.

## Motivation and Context

When pods deployed cross AZs, the active passive reconciler only validate pods belongs to one AZ. 
If the active pod deployed in another AZ, then the component will be unavaialbe.

#17 

## Checklist:

Check item if necessary.

- [ ] Review PRs of changed Quarks dependencies
- [ ] Update this PR after the release of Quarks dependencies

2020-10-13 09:35 UTC, rohitsakala commented
Looks good to me. We will discuss the issue and PR https://github.com/cloudfoundry-incubator/quarks-statefulset/issues/17 in our plannings (Every Monday).

2020-10-20 13:14 UTC, rohitsakala approved these changes

2020-10-22 09:20 UTC, manno commented
It would be great to keep the integration test. Added this story to modify `.github/kind-config.yaml` to add another worker and node labels: https://www.pivotaltracker.com/story/show/171304400

2020-10-22 09:35 UTC, manno requested changes
Could you try the test after https://github.com/cloudfoundry-incubator/quarks-statefulset/pull/22 is merged?

2020-10-22 12:17 UTC, manno approved these changes
Including the first multi az test! 👏

2020-10-22 12:17 UTC, merged